### ISSUE TITLE
Setup homepage grid of Choices

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#3]
The homepage should show a grid of all choice pages. Ideally would show if the user has or hasn't read the page.

![climatechoice-site sketch 2019-05-08 18-49-39](https://user-images.githubusercontent.com/310547/57392819-10258800-71c2-11e9-91fd-439ec140e45b.png)

**Comment by shylands** [comment]
@ThePaulMcBride Don't suppose you have any idea how to go about adding an indicator if a page has been read or not?

**Comment by ThePaulMcBride** [comment]
There are a few ways we could do this. The simplest was is probably using the CSS `visited` [psudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited), though it might not be suitable if the html doesn't quite match up to what we'd need.

Otherwise, we could store the information of what pages you've viewed in local storage or something. Is this already built? If so, I can have a stab at hooking it up.

**Comment by shylands** [comment]
Not yet, should come together over the next day or 2, thanks!

**Comment by shylands** [comment]
@ThePaulMcBride Hey I've started to set these layouts up, see #20.

My current plan is to just build the pages and homepage grid statically, as otherwise, I'll waste too much time working out how to pull everything in dynamically. **My question is does that affect the ability to do the read status at some point?** Thanks

**Comment by ThePaulMcBride** [comment]
Nope, that shouldn't be a problem!
